import os


class Config:
    AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN")
    AUTH0_CLIENT_ID = os.getenv("AUTH0_CLIENT_ID")
    AUTH0_CLIENT_SECRET = os.getenv("AUTH0_CLIENT_SECRET")
    AUTH0_API_IDENTIFIER = os.getenv("AUTH0_API_IDENTIFIER")
    AUTH0_API_AUDIENCE = os.getenv("AUTH0_API_AUDIENCE")
